name: Build main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Comet
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: |
        dotnet workload restore --ignore-failed-sources --skip-sign-check

    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0

    - name: Pack
      run: dotnet pack src/Comet/Comet.csproj -c Release -p:PackageVersion='${{ steps.previoustag.outputs.tag }}-main.${{ github.run_number }}' -p:Symbols -p:SymbolPackageFormat=snupkg  --output packages

    - name: Upload to GitHub registry
      run: |
        dotnet nuget add source --username InterShare --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/julian-baumann/index.json"
        dotnet nuget push "packages/Comet.${{ steps.previoustag.outputs.tag }}-develop.${{ github.run_number }}.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-Package
        path: packages
